import React, { useState, useRef } from 'react';
import { Upload, FileText, CheckCircle, XCircle, Loader2, Download, AlertCircle, Cpu, Eye, Edit3, Save, X, File, MapPin, Building2, Landmark, Hash, FileCheck, TrendingUp, Clock, CheckCircle2 } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { processLandRecord, LandRecord } from '../services/geminiService';
import * as XLSX from 'xlsx';
import { cn } from '../lib/utils';

interface DashboardProps {
  onRecordProcessed: (record: LandRecord) => void;
  history: LandRecord[];
}

export const Dashboard: React.FC<DashboardProps> = ({ onRecordProcessed, history }) => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [currentRecord, setCurrentRecord] = useState<LandRecord | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editedRecord, setEditedRecord] = useState<LandRecord | null>(null);
  const [showOriginal, setShowOriginal] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsProcessing(true);
    setError(null);
    setCurrentRecord(null);
    setIsEditing(false);
    setShowOriginal(false);

    try {
      const result = await processLandRecord(file);
      const fileUrl = URL.createObjectURL(file);
      const recordWithUrl = { ...result, fileUrl };
      setCurrentRecord(recordWithUrl);
      setEditedRecord(recordWithUrl);
      onRecordProcessed(recordWithUrl);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unexpected error occurred.");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSaveEdit = () => {
    if (editedRecord) {
      setCurrentRecord(editedRecord);
      onRecordProcessed(editedRecord);
      setIsEditing(false);
    }
  };

  const exportToExcel = (record: LandRecord) => {
    const gutNumbers = record.gutNumber.split(/[,\s;]+/).map(n => n.trim()).filter(n => n !== "");
    
    const headerRows = [
      ["Udayam AI Labs - Land Record Analysis Report"],
      ["Generated by: Udayam Land Intelligence AI"],
      ["Designed by: Udayraj Patare"],
      ["Date: " + new Date().toLocaleString()],
      [],
      ["Village Name", "Taluka Name", "District Name", "Gut Number", "Status", "Confidence", "Reasoning"]
    ];

    const dataRows = gutNumbers.length > 0 
      ? gutNumbers.map(gut => [
          record.villageName, 
          record.talukaName, 
          record.districtName, 
          gut, 
          record.status, 
          record.confidence + "%", 
          record.reasoning
        ])
      : [[
          record.villageName, 
          record.talukaName, 
          record.districtName, 
          record.gutNumber, 
          record.status, 
          record.confidence + "%", 
          record.reasoning
        ]];

    const ws = XLSX.utils.aoa_to_sheet([...headerRows, ...dataRows]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Land Record");
    XLSX.writeFile(wb, `ULI_AI_Record_${gutNumbers[0] || 'Export'}.xlsx`);
  };

  const getStatusVariant = (status: string) => {
    if (status === 'मंजूर') return 'default';
    if (status === 'नामंजूर') return 'destructive';
    return 'secondary';
  };

  const approvedCount = history.filter(r => r.status === 'मंजूर').length;
  const rejectedCount = history.filter(r => r.status === 'नामंजूर').length;
  const totalProcessed = history.length;

  return (
    <div className="w-full space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Total Processed</p>
              <p className="text-2xl font-bold text-slate-900 mt-1">{totalProcessed}</p>
            </div>
            <div className="p-3 bg-blue-100 rounded-lg">
              <FileCheck className="w-5 h-5 text-blue-600" />
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Approved</p>
              <p className="text-2xl font-bold text-emerald-600 mt-1">{approvedCount}</p>
            </div>
            <div className="p-3 bg-emerald-100 rounded-lg">
              <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Rejected</p>
              <p className="text-2xl font-bold text-rose-600 mt-1">{rejectedCount}</p>
            </div>
            <div className="p-3 bg-rose-100 rounded-lg">
              <XCircle className="w-5 h-5 text-rose-600" />
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">This Month</p>
              <p className="text-2xl font-bold text-slate-900 mt-1">{new Date().toLocaleDateString('en-IN', { month: 'short', year: 'numeric' })}</p>
            </div>
            <div className="p-3 bg-amber-100 rounded-lg">
              <TrendingUp className="w-5 h-5 text-amber-600" />
            </div>
          </div>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Side - Upload Section */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="bg-blue-600 p-5">
              <h3 className="text-white font-bold flex items-center gap-2">
                <Upload className="w-5 h-5" />
                Upload Document
              </h3>
              <p className="text-white/80 text-xs mt-1">Upload Marathi land record documents</p>
            </div>
            <div className="p-8">
              <input 
                type="file" 
                ref={fileInputRef} 
                onChange={handleFileUpload} 
                className="hidden" 
                accept="image/*,application/pdf"
              />
              
              <div 
                className={cn(
                  "border-2 border-dashed rounded-xl p-10 text-center cursor-pointer transition-all",
                  isProcessing ? "border-blue-600 bg-blue-600/5" : "border-slate-200 hover:border-blue-600 hover:bg-slate-50"
                )}
                onClick={() => fileInputRef.current?.click()}
              >
                {isProcessing ? (
                  <div className="space-y-4">
                    <div className="relative w-20 h-20 mx-auto">
                      <Loader2 className="w-20 h-20 text-blue-600 animate-spin" />
                      <div className="absolute inset-0 flex items-center justify-center">
                        <Cpu className="w-8 h-8 text-blue-600" />
                      </div>
                    </div>
                    <div>
                      <p className="font-bold text-slate-900">Analyzing Document...</p>
                      <p className="text-xs text-slate-500 mt-1">Extracting land record data</p>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className="w-14 h-14 bg-slate-100 rounded-full mx-auto flex items-center justify-center mb-4">
                      <Upload className="w-6 h-6 text-slate-400" />
                    </div>
                    <p className="font-semibold text-slate-900">Click to upload</p>
                    <p className="text-xs text-slate-500 mt-2">JPG, PNG, PDF supported</p>
                  </>
                )}
              </div>

              {error && (
                <div className="mt-4 p-3 bg-red-50 border border-red-100 rounded-lg flex items-center gap-2 text-red-700 text-sm">
                  <AlertCircle className="w-4 h-4 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right Side - Results Section */}
        <div className="lg:col-span-2">
          {currentRecord ? (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden h-full">
              <div className="bg-slate-900 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <FileText className="w-5 h-5 text-blue-600" />
                  <div>
                    <h3 className="text-white font-semibold">Analysis Result</h3>
                    <p className="text-white/60 text-xs">{currentRecord.fileName}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <button 
                    className={cn(
                      "px-3 py-1.5 rounded-lg text-sm font-medium transition-colors",
                      showOriginal ? "bg-white text-slate-900" : "bg-white/10 text-white hover:bg-white/20"
                    )}
                    onClick={() => setShowOriginal(!showOriginal)}
                  >
                    <Eye className="w-4 h-4 inline mr-1" />
                    {showOriginal ? "Hide" : "View"}
                  </button>
                  <span className={cn(
                    "px-3 py-1.5 rounded-lg text-sm font-bold flex items-center gap-1",
                    currentRecord.status === 'मंजूर' ? "bg-emerald-500 text-white" : 
                    currentRecord.status === 'नामंजूर' ? "bg-rose-500 text-white" : "bg-amber-500 text-white"
                  )}>
                    {currentRecord.status === 'मंजूर' ? <CheckCircle className="w-3 h-3" /> : <XCircle className="w-3 h-3" />}
                    {currentRecord.status}
                  </span>
                </div>
              </div>

              <div className="p-6">
                <div className="flex items-center justify-between mb-6">
                  <h4 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    Extracted Information
                    {isEditing && <span className="text-xs font-medium text-amber-600 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">Editing</span>}
                  </h4>
                  <div className="flex items-center gap-2">
                    {!isEditing ? (
                      <button 
                        className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-slate-600 hover:text-blue-600 transition-colors"
                        onClick={() => setIsEditing(true)}
                      >
                        <Edit3 className="w-4 h-4" />
                        Edit
                      </button>
                    ) : (
                      <>
                        <button 
                          className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-emerald-600 hover:text-emerald-700"
                          onClick={handleSaveEdit}
                        >
                          <Save className="w-4 h-4" />
                          Save
                        </button>
                        <button 
                          className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-rose-600 hover:text-rose-700"
                          onClick={() => { setIsEditing(false); setEditedRecord(currentRecord); }}
                        >
                          <X className="w-4 h-4" />
                          Cancel
                        </button>
                      </>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">
                          <MapPin className="w-3 h-3 inline mr-1" /> Village
                        </label>
                        {isEditing ? (
                          <input 
                            type="text" 
                            value={editedRecord?.villageName || ""}
                            onChange={(e) => setEditedRecord(prev => prev ? { ...prev, villageName: e.target.value } : null)}
                            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm font-medium focus:outline-none focus:border-blue-600"
                          />
                        ) : (
                          <p className="text-base font-semibold text-slate-800">{currentRecord.villageName}</p>
                        )}
                      </div>
                      <div>
                        <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">
                          <Building2 className="w-3 h-3 inline mr-1" /> Taluka
                        </label>
                        {isEditing ? (
                          <input 
                            type="text" 
                            value={editedRecord?.talukaName || ""}
                            onChange={(e) => setEditedRecord(prev => prev ? { ...prev, talukaName: e.target.value } : null)}
                            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm font-medium focus:outline-none focus:border-blue-600"
                          />
                        ) : (
                          <p className="text-base font-semibold text-slate-800">{currentRecord.talukaName}</p>
                        )}
                      </div>
                      <div>
                        <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">
                          <Landmark className="w-3 h-3 inline mr-1" /> District
                        </label>
                        {isEditing ? (
                          <input 
                            type="text" 
                            value={editedRecord?.districtName || ""}
                            onChange={(e) => setEditedRecord(prev => prev ? { ...prev, districtName: e.target.value } : null)}
                            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm font-medium focus:outline-none focus:border-blue-600"
                          />
                        ) : (
                          <p className="text-base font-semibold text-slate-800">{currentRecord.districtName}</p>
                        )}
                      </div>
                      <div>
                        <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">
                          <Hash className="w-3 h-3 inline mr-1" /> Gut No.
                        </label>
                        {isEditing ? (
                          <input 
                            type="text" 
                            value={editedRecord?.gutNumber || ""}
                            onChange={(e) => setEditedRecord(prev => prev ? { ...prev, gutNumber: e.target.value } : null)}
                            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm font-medium focus:outline-none focus:border-blue-600"
                          />
                        ) : (
                          <p className="text-base font-semibold text-slate-800">{currentRecord.gutNumber}</p>
                        )}
                      </div>
                    </div>
                    
                    <div className="pt-4 border-t border-slate-100">
                      <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">Confidence Score</label>
                      <div className="flex items-center gap-3">
                        <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                          <div 
                            className={cn(
                              "h-full rounded-full transition-all",
                              currentRecord.confidence > 80 ? "bg-emerald-500" : 
                              currentRecord.confidence > 50 ? "bg-amber-500" : "bg-rose-500"
                            )}
                            style={{ width: `${currentRecord.confidence}%` }}
                          />
                        </div>
                        <span className="text-sm font-bold text-slate-700">{currentRecord.confidence}%</span>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="bg-slate-50 rounded-lg p-4">
                      <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">AI Reasoning</label>
                      <p className="text-sm text-slate-600 italic">"{currentRecord.reasoning}"</p>
                    </div>
                    
                    <button
                      onClick={() => exportToExcel(currentRecord)}
                      className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors"
                    >
                      <Download className="w-5 h-5" />
                      Download Excel Report
                    </button>
                    {currentRecord.gutNumber.split(/[,\s;]+/).filter(n => n.trim() !== "").length > 1 && (
                      <p className="text-xs text-slate-400 text-center">Multiple Gut Numbers will be exported as separate rows</p>
                    )}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 h-full flex flex-col items-center justify-center">
              <div className="w-20 h-20 bg-slate-100 rounded-full mx-auto flex items-center justify-center mb-4">
                <FileText className="w-10 h-10 text-slate-300" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">No Document Processed</h3>
              <p className="text-sm text-slate-500 mt-2">Upload a document to see analysis results here</p>
            </div>
          )}

          {/* Original Document Preview */}
          {showOriginal && currentRecord?.fileUrl && (
            <div className="mt-6 bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="bg-slate-100 px-6 py-3 flex items-center justify-between border-b">
                <h4 className="font-semibold text-slate-700">Original Document</h4>
                <button onClick={() => setShowOriginal(false)} className="p-1 hover:bg-slate-200 rounded">
                  <X className="w-4 h-4 text-slate-500" />
                </button>
              </div>
              <div className="p-4 bg-slate-50 max-h-[400px] overflow-auto flex justify-center">
                {currentRecord.fileName.toLowerCase().endsWith('.pdf') ? (
                  <div className="text-center py-8">
                    <File className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                    <p className="text-sm text-slate-500 mb-3">PDF Preview might be blocked</p>
                    <a 
                      href={currentRecord.fileUrl} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-sm text-blue-600 hover:underline"
                    >
                      Open PDF in New Tab →
                    </a>
                  </div>
                ) : (
                  <img 
                    src={currentRecord.fileUrl} 
                    alt="Original Document" 
                    className="max-w-full h-auto rounded shadow"
                    referrerPolicy="no-referrer"
                  />
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
