import React from 'react';
import { Clock, Download, ChevronRight, FileText, Eye } from 'lucide-react';
import { LandRecord } from '../services/geminiService';
import { cn } from '../lib/utils';
import * as XLSX from 'xlsx';

interface HistoryProps {
  records: LandRecord[];
}

export const History: React.FC<HistoryProps> = ({ records }) => {
  const exportAllToExcel = () => {
    if (records.length === 0) return;

    const headerRows = [
      ["Udayam AI Labs - Land Record Analysis History Report"],
      ["Generated by: Udayam Land Intelligence AI"],
      ["Designed by: Udayraj Patare"],
      ["Date: " + new Date().toLocaleString()],
      [],
      ["Date Processed", "File Name", "Village Name", "Taluka Name", "District Name", "Gut Number", "Status", "Confidence", "Reasoning"]
    ];

    const dataRows: any[] = [];
    records.forEach(r => {
      // Split by comma, space, or semicolon to be robust
      const gutNumbers = r.gutNumber.split(/[,\s;]+/).map(n => n.trim()).filter(n => n !== "");
      const timestamp = new Date(r.timestamp).toLocaleString();
      
      if (gutNumbers.length > 0) {
        gutNumbers.forEach(gut => {
          dataRows.push([
            timestamp,
            r.fileName,
            r.villageName,
            r.talukaName,
            r.districtName,
            gut,
            r.status,
            r.confidence + "%",
            r.reasoning
          ]);
        });
      } else {
        dataRows.push([
          timestamp,
          r.fileName,
          r.villageName,
          r.talukaName,
          r.districtName,
          r.gutNumber,
          r.status,
          r.confidence + "%",
          r.reasoning
        ]);
      }
    });

    const ws = XLSX.utils.aoa_to_sheet([...headerRows, ...dataRows]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "History");
    XLSX.writeFile(wb, `ULI_AI_History_Export.xlsx`);
  };

  return (
    <div className="space-y-6 w-full">
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-udayam-purple rounded-lg">
            <Clock className="w-5 h-5 text-white" />
          </div>
          <h2 className="text-2xl font-bold text-slate-900">Processing History</h2>
        </div>
        
        {records.length > 0 && (
          <button
            onClick={exportAllToExcel}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-semibold text-slate-700 hover:bg-slate-50 transition-colors shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export All to Excel
          </button>
        )}
      </div>

      {records.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-200">
          <FileText className="w-12 h-12 text-slate-200 mx-auto mb-4" />
          <p className="text-slate-500 font-medium">No records processed yet.</p>
          <p className="text-sm text-slate-400">Start by uploading a document in the Dashboard.</p>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Date</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Document</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Gut No/s.</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Location</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider text-center">Status</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-wider text-right">Confidence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {records.map((record) => (
                  <tr key={record.id} className="hover:bg-slate-50 transition-colors group">
                    <td className="px-6 py-4">
                      <p className="text-xs font-medium text-slate-500">
                        {new Date(record.timestamp).toLocaleDateString()}
                      </p>
                      <p className="text-[10px] text-slate-400">
                        {new Date(record.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </p>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-semibold text-slate-800 truncate max-w-[150px]">
                          {record.fileName}
                        </p>
                        {record.fileUrl && (
                          <a 
                            href={record.fileUrl} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="p-1 text-slate-400 hover:text-udayam-purple transition-colors"
                            title="View Original Document"
                          >
                            <Eye className="w-4 h-4" />
                          </a>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-sm font-mono font-medium text-slate-600">
                        {record.gutNumber}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <p className="text-sm text-slate-600">
                        {record.villageName}, {record.talukaName}
                      </p>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex justify-center">
                        <span className={cn(
                          "px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider",
                          record.status === 'मंजूर' ? "bg-emerald-100 text-emerald-700" : 
                          record.status === 'नामंजूर' ? "bg-rose-100 text-rose-700" :
                          "bg-amber-100 text-amber-700"
                        )}>
                          {record.status}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <span className={cn(
                        "text-sm font-bold",
                        record.confidence > 80 ? "text-emerald-600" : 
                        record.confidence > 50 ? "text-amber-600" : "text-rose-600"
                      )}>
                        {record.confidence}%
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};
